In [1]:
import matplotlib
%matplotlib tk
%autosave 180
%load_ext autoreload
%autoreload 2

import nest_asyncio
%config Completer.use_jedi = False

#
import matplotlib.pyplot as plt
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

import scipy
import numpy as np
import pandas as pd
import os
os.chdir('/home/cat/code/manifolds')

from calcium import calcium
from wheel import wheel
from visualize import visualize
from tqdm import trange

import networkx as nx
import pandas as pd
from mne.viz import plot_connectivity_circle



import numpy as np
import scipy
from scipy.io import loadmat

from tqdm import tqdm, trange

Autosaving every 180 seconds


In [2]:
   
def compute_ensemble_occurance(c, selected_ensemble,
                              recompute=True):
    
    
    fname_out = os.path.join(c.root_dir,
                            c.animal_id,
                            c.session,
                            'suite2p',
                            'plane0',
                            'ensembles',
                            'ens_times.npy')
    
    if os.path.exists(fname_out)==False or recompute:
        ensemble_ids = np.arange(selected_ensemble.shape[0])

        #
        ens_times = []
        #ens_network = []
        for ensemble_id in tqdm(ensemble_ids):
            ww = np.zeros(rasters.shape[1])
            idx = selected_ensemble[ensemble_id].squeeze()
            #print (idx)
            ww[idx] = 1

            W = np.outer(ww,ww)
            #print ("W: ", W.shape)
            # set single occurances to zero!
            np.fill_diagonal(W,0)
            #print ("W: ", W.shape)
            
            #
            f = np.zeros(Zib.shape[0])
            s = np.zeros(Zib.shape)
            for t in range(Zib.shape[0]):
                temp1 = np.matmul(Zib[t].T,W)
                temp2 = np.matmul(temp1,Zib[t])
                f[t]=temp2

#                 #
#                 for i in idx:
#                     if Zib[t,i]>=thresh:
#                         s[t,i]=1

            #
            ens_times.append(f)
            #ensemble_stacks.append(s)
        
        np.save(fname_out, ens_times)
        
        ens_times = np.array(ens_times)
    else:
        ens_times = np.load(fname_out)
            
        
    return ens_times
        
        
def plot_ensemble_occurances(ens_times, 
                            w):     
        
    # downsample track times to match data that went into Matlab ICA routines
    factor = 15
    vel_down = w.track.velocity.values.reshape(-1,factor).mean(axis=1)
    vel_times = w.track.velocity.times.reshape(-1,factor).mean(axis=1)
    print (vel_down.shape)

    #
    ctr=0
    #fig=plt.figure()
    ensemble_times = []
    ensemble_stacks = []
    thresh = 0

    y_scale = 40000

    if False:
        plt.plot(times, vel_down*2E5-y_scale*2,
            c='black',
            linewidth=2)
    else:
        plt.plot(w.track.velocity.times,
                 w.track.velocity.values*2E5-y_scale*2,
            c='black',
            linewidth=2)

    times = vel_times
    ensemble_ids = np.arange(ens_times.shape[0])
    
    print ("# of ensembels: ", ensemble_ids)
    
    for k in range(ensemble_ids.shape[0]):

        f = ens_times[k]        
        # 
        if True:
            plt.plot(times,f+ctr*y_scale)
        else:
            plt.plot(times, np.log(f+0.0001)+ctr*25)
        plt.xlabel("Time (sec)")
        plt.ylabel("Ensemble ID")

        # plot shaded version also
        if True:
            plt.plot(w.track.velocity.times,
                 w.track.velocity.values*5E4+ctr*y_scale,
            c='black',
            alpha=.2,)



        ctr+=1


    ylabels1 = np.arange(0,ctr*y_scale, y_scale)
    ylabels2 = np.arange(len(ensemble_ids))
    plt.yticks(ylabels1,ylabels2)
    #
    #plt.yticks([])
    plt.show()

def plot_ensemble(row,col,ens_id,ax_ctr,
                 selected_ensemble,
                 c,
                 graphs):
    
    ax=plt.subplot(row,col,ax_ctr+1)
    plt.xticks([])
    plt.yticks([])

    ids = selected_ensemble[ens_id].squeeze()
    #print (ids)
    for id2 in ids:
        contour = c.get_footprint_contour(id2)
        plt.plot(contour[:,1],
                contour[:,0],
                c='black')

    cmap = plt.get_cmap("viridis", 10)
    # normalize connectivity within each graph
    graph1 = graphs[ens_id]
    if True:
        graph1 = (graph1-np.min(graph1))/(np.max(graph1)-np.min(graph1))#+0.01
        
    # scale the colros up
    if True:
        graph1*=1
        graph1 = np.clip(graph1,0,.5)
    #else:
    #    graph1 = np.log(graph1+1.0)
        
        
    for k in trange(graph1.shape[0]):
        for p in range(k+1, graph1.shape[0],1):
            centre1 = c.get_footprint_contour(ids[k]).mean(0)
            centre2 = c.get_footprint_contour(ids[p]).mean(0)
            cb = plt.plot(
                    [centre1[1], centre2[1]],
                    [centre1[0], centre2[0]],
                    linewidth = graph1[k,p]*10,
                    #color='red',
                    color=cmap(int(graph1[k,p]*20)),
                    alpha=.2
                    )
            
                # 
    sm = plt.cm.ScalarMappable(cmap=cmap, 
                               norm=plt.Normalize(vmin=0, vmax=.5))
    plt.colorbar(sm)



    
    plt.xlim(0,512)
    plt.ylim(0,512)

    return ax, cb

   
def compute_ensemble_graph(c, selected_ensemble):
    
    
    fname_out = os.path.join(c.root_dir,
                            c.animal_id,
                            c.session,
                            'suite2p',
                            'plane0',
                            'ensembles',
                            'ens_graphs.npy')
    
    if os.path.exists(fname_out)==False:
        
        factor=15
        Z = c.F_upphase_bin.T
        Z_down = []
        for k in range(0,Z.shape[0],factor):
            temp = Z[k:k+factor]
            Z_down.append(temp.max(0))
            
        Z_down = np.vstack(Z_down)
        print (Z_down.shape)
        
        ensemble_ids = np.arange(selected_ensemble.shape[0])

        #
        ens_graphs = []
        for ensemble_id in tqdm(ensemble_ids):
            #ww = np.zeros(rasters.shape[1])
            idx = selected_ensemble[ensemble_id].squeeze()
            #print (ensemble_id, idx.shape)

            graph = np.zeros((idx.shape[0],
                             idx.shape[0]))
            
            # 
            for t in range(Z_down.shape[0]):
                temp = Z_down[t]
                #print ("time slice; ", temp)
                temp2 = temp[idx]
                #print ("indexed time slice; ", temp)
                idx2 = np.where(temp2>0)[0]
                
                for i in range(idx2.shape[0]):
                    for p in range(i+1,idx2.shape[0],1):
                        graph[idx2[i],idx2[p]]+=1
                        #print ("adding")

            #
            ens_graphs.append(graph)
            #ensemble_stacks.append(s)
        
        np.save(fname_out, ens_graphs)
    else:
        ens_graphs = np.load(fname_out)
            
            
    return ens_graphs, Z_down



In [3]:
##########################################################
############ ALTERNATIVE: GET RASTERS FROM DF_F ##########
##########################################################
root_dir = '/media/cat/4TB/donato/'
animal_id = 'DON-006084'
session = '20210519'

binarization_method='upphase'

#
c = calcium.Calcium()
c.root_dir = root_dir
c.animal_id = animal_id
c.session = session
c.load_suite2p()

# 
c.load_binarization()
if binarization_method=='onphase':
    traces = c.F_onphase_bin
elif binarization_method=='upphase':
    traces = c.F_upphase_bin
else:
    print ("METHOD NOT FOUND")


c.load_footprints()
    
print ("binarized data: ", traces.shape)

w = wheel.Wheel()
w.root_dir = os.path.join(root_dir,
                          animal_id,
                          session,
                          'TRD-2P')
w.animal_id = animal_id
w.session = session
w.load_track()
w.compute_velocity()

    
# these are binned rasters use specifically for Matlab SGC/ICA ensemble detection
rasters = np.load(os.path.join(root_dir,
                              animal_id,
                              session,
                              'suite2p',
                              'plane0',
                              'ensembles',
                              'F_upphase_binned_sum.npy'))
print ("Rasters (time:#cells): ", rasters.shape)

# if False:
#     plt.imshow(rasters.T,
#               aspect='auto',
#               #vmin=0,
#               #vmax=1
#                interpolation='none'
#               )
#     plt.show()



(531, 55740)
binarized data:  (531, 55740)
Rasters (time:#cells):  (3716, 531)


In [4]:
#######################################################
################ Z-SCORE RASTERS ######################
#######################################################
Zib = np.zeros(rasters.shape)
print ("Zib: ", Zib.shape)

# compute standard deviations
sigma = np.std(rasters,axis=0)
print ("sigma: ", sigma.shape)

# compute means
means = np.mean(rasters,axis=0)
print ("means: ", means.shape)

# compute normalized projectuion
for t in trange(Zib.shape[0]):
    for q in range(Zib.shape[1]):
        Zib[t,q]= (rasters[t,q]-means[q])/sigma[q]
    


Zib:  (3716, 531)
sigma:  (531,)
means:  (531,)


100%|█████████████████████████████████████████████████████████████████| 3716/3716 [00:02<00:00, 1812.83it/s]


In [12]:
#######################################################
################## LOAD ASSEMBLIES ####################
#######################################################
fname =  os.path.join(root_dir,
                      animal_id,
                      session,
                      'suite2p',
                      'plane0',
                      'ensembles',
                      'Upphase_sum_binned_ICA_ASSEMBLIES.mat')

# 
data = loadmat(fname)
#print (data.keys())
ens_mp = data['mp_assemblies'].squeeze()-1
ens_cs = data['cs_assemblies'].squeeze()-1

# 
print ("Cs ensembles: ", ens_cs.shape)
print ("Mp ensembles: ", ens_mp.shape)
fname =  os.path.join(root_dir,
                      animal_id,
                      session,
                      'suite2p',
                      'plane0',
                      'ensembles',
                      'Upphase_sum_binned_SGC-ASSEMBLIES.mat')

data = loadmat(fname)
#print (data.keys())
assemblies = data['assemblies'].squeeze()-1
assembly_pattern_detection = data['assembly_pattern_detection'].squeeze()

print ("SGC assembiles ", assemblies.shape)
#print ("assembly_pattern_detection: ", assembly_pattern_detection.shape)
    
    
#
#w = np.zeros(rasters.shape[1])


Cs ensembles:  (25,)
Mp ensembles:  (65,)
SGC assembiles  (8,)


In [24]:
######################################################
######## GET ENSEMBLE OCCURANCES AND VISUALIZE #######
######################################################
# NOTE need to delete previous ens_times.npy file to reprocess new data
selected_ensembles = ens_cs.copy()
#selected_ensembles = ens_mp.copy()
#selected_ensembles = assemblies.copy()

print ("selected_ensembles: ", selected_ensembles.shape)
recompute = True
ens_times= compute_ensemble_occurance(c, selected_ensembles,
                                      recompute)
fig=plt.figure(figsize=(20,20))
plot_ensemble_occurances(ens_times, w)

if False:
    plt.savefig('/home/cat/ensembles.svg')
    plt.close()
else:
    plt.show()

selected_ensembles:  (25,)


100%|███████████████████████████████████████████████████████████████████████| 25/25 [00:08<00:00,  2.82it/s]


(3716,)
# of ensembels:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [33]:
######################################################
######## GET ENSEMBLE OCCURANCES AND VISUALIZE #######
######################################################

#
ensemble_id = 13
neuron_ids = selected_ensembles[ensemble_id].squeeze()
print ("neuron ids: ", neuron_ids)

#
print (ens_times[ensemble_id].shape)
temp = ens_times[ensemble_id]
median = np.median(ens_times)
idx = np.where(temp>median)[0]

idx = np.arange(temp.shape[0])

# 
print ("rasters: ", rasters.shape)
rasters_ensemble = rasters[idx][:, neuron_ids]
print (rasters.shape, rasters_ensemble.shape)

sums = rasters_ensemble.sum(0)
print (sums.shape)
idx2 = np.argsort(sums)[::-1]
rasters_ensemble = rasters_ensemble[:,idx2]


fig=plt.figure()
# ax=plt.subplot(211)
# plt.plot(ens_times[ensemble_id])

# extract ensemble occurance time series
temp2 = ens_times[ensemble_id,idx]
idx3 = np.argsort(temp2)[::-1]
xlabels = [
    #'Time bins in which ensemble is active (0.5 sec bins)',
    'Time bins (0.5 sec bins)',
           "Reordered Time bin (0.5 sec bins)"]

# extract binarized mua for all celss
temp3 = rasters_ensemble.copy()
temp3 = np.clip(temp3, 0,1)
mua_binarized = np.sum(temp3, axis=1)
print ("mua_binarized.sh", mua_binarized.shape)




if False:
    for p in range(2):
        ax=plt.subplot(2,1,p+1)

        if p==1:
            rasters_ensemble = rasters_ensemble[idx3]
            temp2 = temp2[idx3]

        plt.xlabel(xlabels[p])
        temp2 = temp2/np.max(temp2)*rasters_ensemble.shape[1]
        plt.plot(temp2, 
                c='red')

        #
        plt.imshow(rasters_ensemble.T,
                  aspect='auto',
                  extent=[0,rasters_ensemble.shape[0], 0, rasters_ensemble.shape[1]],
                  interpolation='none'
                  )


        plt.ylabel("Neuron Id within the ensemble")
else:
    ax=plt.subplot(1,1,1)

    plt.xlabel(xlabels[0])
    temp2 = temp2/np.max(temp2)*rasters_ensemble.shape[1]
    plt.plot(temp2, 
            c='red',
            alpha=.5)
    
    
    mua_binarized = mua_binarized/np.max(mua_binarized)*rasters_ensemble.shape[1]
    plt.plot(mua_binarized,
            c='white',
            alpha=.5)

    #
    plt.imshow(rasters_ensemble.T,
              aspect='auto',
              extent=[0,rasters_ensemble.shape[0], 0, rasters_ensemble.shape[1]],
              interpolation='none'
              )


    plt.ylabel("Neuron Id within the ensemble")        
        
plt.suptitle("Total neurons: "+str(rasters.shape[1])+ ", selected ensemble ID: "+str(ensemble_id))

plt.show()


neuron ids:  [ 20  24  56  84  99 113 120 139 140 148 149 195 217 258 287 324 341 345
 366 386 406 443 452 458 489 491 527]
(3716,)
rasters:  (3716, 531)
(3716, 531) (3716, 27)
(27,)
mua_binarized.sh (3716,)


In [29]:
######################################################
######## BUILD ENSEMBLE GRAPH BASED ON OCCURANCE #####
######################################################
#selected_ensembles = assemblies.copy()

graphs, Z_down = compute_ensemble_graph(c, selected_ensembles)
    


(3716, 531)


100%|███████████████████████████████████████████████████████████████████████| 25/25 [00:01<00:00, 23.16it/s]
/home/cat/anaconda3/envs/manifolds/lib/python3.8/site-packages/numpy/lib/npyio.py:528: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.asanyarray(arr)


In [30]:
###############################################
############# SPATIAL GRAPH ############
###############################################

# plot all ensembles
if False:
    ens_ids = np.arange(25)
    fig=plt.figure(figsize=(40,20))
    row=5
    col=5
    
# plot only selected ones
else:
    ens_ids = [0,4]
    row=1
    col=1
    

for ens_id in tqdm(ens_ids):
    fig=plt.figure() # move this outside for all cells
    
    #ax_ctr=end_ids
    ax_ctr=0
    
    ax, cb = plot_ensemble(row,col,ens_id,ax_ctr,
                 selected_ensemble,
                 c,
                 graphs)

    plt.tight_layout()
    plt.show()


#plt.suptitle("ICA-CS Ensembles")
if False:
    plt.savefig('/home/cat/ensmbles.svg')
    plt.close()
    
else:
    plt.show()


100%|█████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.58it/s]


In [31]:
########################################
############ NETWORK GRAPHS ############
########################################

import networkx as nx

ids = np.arange(len(graphs))
#fig = plt.figure(figsize=(40,20))
ids = [14,19]
for i in ids:
    #plt.subplot(5,5,i+1)
    fig=plt.figure()
    G = nx.Graph()
    graph = graphs[i]
    
    if True:
        graph = (graph-np.min(graph))/(np.max(graph)-np.min(graph))/0.4
#     if True:
#         graph = graph#**3
        
    # 
    if False:
        ax1=plt.subplot(1,2,1)
        y=np.histogram(graph, bins=np.arange(0,1.05,0.05))
        plt.plot(y[1][:-1],y[0])
        plt.semilogy()
    
    #ax2=plt.subplot(1,2,2)
    if False:
        idx = np.where(graph<0.05)
        graph[idx]=0
    
    print ("Graph: ", graph.shape)
    for k in range(graph.shape[0]):
        for p in range(k+1, graph.shape[0],1):
            G.add_edge(k,p,color='r',weight=graph[k,p])

    colors = nx.get_edge_attributes(G,'color').values()
    weights = nx.get_edge_attributes(G,'weight').values()

    if True:
        nx.draw(G, edge_color=colors, 
            width=list(weights),
            with_labels=True,
            node_color='grey',
            node_size=0,
            font_size=10
               )
    else:
        pos = nx.circular_layout(G)
        nx.draw(G, pos, 
            edge_color=colors, 
            width=list(weights),
            with_labels=True,
            node_color='grey')
        
        
    plt.title(str(i))
    
    
if False:
    plt.savefig('/home/cat/net.svg')
    plt.close()
else:
    plt.show()

Graph:  (22, 22)
Graph:  (30, 30)


In [319]:
 ########################################

import networkx as nx

ids = np.arange(len(graphs))
#fig = plt.figure(figsize=(40,20))
ids = [14,19]
for i in ids:
    #plt.subplot(5,5,i+1)
    fig=plt.figure()
    G = nx.Graph()
    graph = graphs[i]
    
    if True:
        graph = (graph-np.min(graph))/(np.max(graph)-np.min(graph))/0.4
    if True:
        graph = graph#**3
        
    # 
    ax1=plt.subplot(1,2,1)
    y=np.histogram(graph, bins=np.arange(0,1.05,0.05))
    plt.plot(y[1][:-1],y[0])
    plt.semilogy()
    
    ax2=plt.subplot(1,2,2)
    if False:
        idx = np.where(graph<0.05)
        graph[idx]=0
    
    print ("Graph: ", graph.shape)
    for k in range(graph.shape[0]):
        for p in range(k+1, graph.shape[0],1):
            G.add_edge(k,p,color='r',weight=graph[k,p])

    colors = nx.get_edge_attributes(G,'color').values()
    weights = nx.get_edge_attributes(G,'weight').values()

    pos = nx.circular_layout(G)
    if True:
        nx.draw(G, edge_color=colors, 
            width=list(weights),
            with_labels=True,
            node_color='grey')
    else:
        nx.draw(G, pos, 
            edge_color=colors, 
            width=list(weights),
            with_labels=True,
            node_color='grey')
    plt.title(str(i))
    
    
if False:
    plt.savefig('/home/cat/net.svg')
    plt.close()
else:
    plt.show()

Graph:  (15, 15)
Graph:  (27, 27)


In [283]:
# ########################################
# ########################################
# ########################################

# # plot all ensembles
# if True:
#     ens_ids = np.arange(25)
#     fig=plt.figure(figsize=(40,20))
#     row=5
#     col=5
    
# # plot only selected ones
# else:
#     ens_ids = [0,4]
#     row=1
#     col=1
    

# fig=plt.figure() # move this outside for all cells
# for ens_id in tqdm(ens_ids):
#     ax=plt.subplot(5,5,ens_id+1)

#     N = graphs[ens_id].shape[0]  # Number of nodes
#     node_names = [f"{i}" for i in range(N)]  # List of labels [N]

#     # Random connectivity
#     con = np.float64(graphs[ens_id])
#     con = con + con.T
#     con = (con-np.min(con))/(np.max(con)-np.min(con))#*100

#     plot_connectivity_circle(con, node_names)   

# #plt.suptitle("ICA-CS Ensembles")
# if False:
#     plt.savefig('/home/cat/ensmbles.svg')
#     plt.close()
    
# else:
#     plt.show()
    
    

 72%|█████████████████████████████████████████████████████████████████████████████▊                              | 18/25 [00:05<00:02,  3.40it/s]/home/cat/anaconda3/envs/manifolds/lib/python3.8/site-packages/mne/viz/circle.py:299: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig = plt.figure(figsize=(8, 8), facecolor=facecolor)
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████▎        | 23/25 [00:06<00:00,  3.43it/s]


KeyboardInterrupt: 

In [284]:
# import pylab
# import networkx as nx
# #G=nx.cycle_graph(80)
# id3 = 2
# #G = nx.from_numpy_matrix(graphs[id3])
# ax=plt.subplot(121)

# G = nx.from_numpy_matrix(graphs[id3])

# # 
# layout = nx.spring_layout(G)
# nx.draw(G, layout, node_size=1000, with_labels=True, font_weight='bold',    font_size=15)
# labels = nx.get_edge_attributes(G,'weight')

# nx.draw_networkx_edge_labels(G,
#                              pos=layout,
#                              edge_labels=labels)



# pos=nx.circular_layout(G)
# pylab.figure(1)
# nx.draw(G,pos)

# ax=plt.subplot(122)
# plt.imshow(graphs[id3])


# # pylab.figure(2)
# # nx.draw(G,pos,node_size=60,font_size=8)
# # pylab.figure(3,figsize=(12,12))
# # nx.draw(G,pos)
# pylab.show()

Graph:  (20, 20)
Graph:  (32, 32)


In [77]:
######################################################
################## LOOK AT EACH ######################
######################################################
id_ = 0
sample_rate=2

######################
fig=plt.figure()
ax=plt.subplot(3,1,1)
e = ensemble_times[id_]
plt.plot(times,e)

# 
plt.xlim(0,e.shape[0]/sample_rate)
plt.title("Ensemble: "+str(id_))
plt.ylabel("Ensemble presence (projection)")
plt.ylim(0,10000)


##################
ax=plt.subplot(3,1,2)
ee = ensemble_stacks[id_]
plt.imshow(ee.T,
          aspect='auto',
          interpolation='none',
          extent=[0,ee.shape[0]/sample_rate, 0,ee.shape[1]])
plt.xlabel("Time (sec)")
plt.ylabel("Neuron ID")

##################
ax=plt.subplot(3,1,3)
ee = ensemble_stacks[id_]
sums2 = ee.sum(axis=1)
idx = np.where(sums2>0)[0]
print (idx)
temp = rasters[idx]
print (temp.shape)
plt.imshow(temp,
          aspect='auto',
          interpolation='none',
          extent=[0,temp.shape[0]/sample_rate, 
                  0,temp.shape[1]]
          )
plt.xlabel("Time - discontinuous (sec)")
plt.ylabel("Removed zero-activity frames\nNeuron ID")

plt.show()


[   0    1    2 ... 3713 3714 3715]
(2349, 531)


In [93]:
##################################################
################ LOAD FOOTPRINTS #################
##################################################
root_dir = '/media/cat/4TBSSD/donato/binarized_traces/'
animal_id = ''
session = ''

#
c = calcium.Calcium()
c.animal_id = animal_id
c.root_dir = root_dir
c.session = session
c.recompute = False
c.load_suite2p()

#
c.load_binarization()

# 
c.load_footprints()




(531, 55740)


In [95]:
######################################################
################ VISUALIZE ENSEMBLES #################
######################################################
selected_ensemble = ens_cs.copy()
ensemble_ids = np.arange(selected_ensemble.shape[0])

ensemble_ids = np.arange(8)
cmap = plt.get_cmap("viridis", Zib.shape[1])

fig=plt.figure()

ctr2=0
for ensemble_id in ensemble_ids:
    ax=plt.subplot(3,3,ctr2+1)
    print ("ensemble stack: ", ensemble_times.shape) 
    ens_times = ensemble_times[ensemble_id]
    #print (ens_times.shape)

    idx = np.where(ens_times>50)[0]
    print ("# of occurances: of ensemble over threshold", idx.shape)

    # 
    norms = np.zeros(Zib.shape[1])
    print ("norms: ", norms.shape, "Zib: ", Zib.shape)

    # 
    for ctr,i in enumerate(idx):
        activity = Zib[i]
        idx2 = np.where(activity>0)[0]
        norms[idx2]+=1

    norms = (norms-np.min(norms))/(np.max(norms)-np.min(norms))

    # 
    for n in range(Zib.shape[1]):

        plt.plot(c.contours[n][:,0],
                 c.contours[n][:,1],
                 #color=cmap(n),
                 c='black',
                 linewidth=3,
                 alpha=norms[n]
                )
    plt.xlim(0,512)
    plt.ylim(0,512)
    ctr2+=1
    
plt.show()


ensemble stack:  (8, 3716)
# of occurances: of ensemble over threshold (3366,)
norms:  (531,) Zib:  (3716, 531)
ensemble stack:  (8, 3716)
# of occurances: of ensemble over threshold (2908,)
norms:  (531,) Zib:  (3716, 531)
ensemble stack:  (8, 3716)
# of occurances: of ensemble over threshold (3128,)
norms:  (531,) Zib:  (3716, 531)
ensemble stack:  (8, 3716)
# of occurances: of ensemble over threshold (3176,)
norms:  (531,) Zib:  (3716, 531)
ensemble stack:  (8, 3716)
# of occurances: of ensemble over threshold (3225,)
norms:  (531,) Zib:  (3716, 531)
ensemble stack:  (8, 3716)
# of occurances: of ensemble over threshold (2563,)
norms:  (531,) Zib:  (3716, 531)
ensemble stack:  (8, 3716)
# of occurances: of ensemble over threshold (3130,)
norms:  (531,) Zib:  (3716, 531)
ensemble stack:  (8, 3716)
# of occurances: of ensemble over threshold (3253,)
norms:  (531,) Zib:  (3716, 531)


In [48]:
######################################################
############# VISUALIZE ENSEMBLES OVER TIME ##########
######################################################
selected_ensemble = ens_cs.copy()
ensemble_ids = np.arange(selected_ensemble.shape[0])

ensemble_id = 1
print ("ensemble stack: ", ensemble_times.shape) 
ens_times = ensemble_times[ensemble_id]
print (ens_times.shape)

idx = np.where(ens_times>1000)[0]
print (idx.shape)

cmap = plt.get_cmap("viridis", 531)

for ctr,i in enumerate(idx):
    ax=plt.subplot(5,8,ctr+1)
    activity = c.F_upphase_bin[:,i]
    
    idx2 = np.where(activity>0)[0]
    #print ("idx2: ", idx2)
    for n in idx2:
        plt.plot(c.contours[n][:,0],
                 c.contours[n][:,1],
                 color=cmap(n),
                )
    plt.xlim(0,512)
    plt.ylim(0,512)
    plt.title(str(i))
plt.show()

        

ensemble stack:  (25, 3716)
(3716,)
(86,)


ValueError: num must be 1 <= num <= 40, not 41

In [44]:
#

import networkx as nx

    
def load_correlation_matrix(fname):

    cc = np.load(fname)
    print (cc.shape)
    print (cc[0])

    n_neurons = int(max(int(np.max(cc[:,0])),int(np.max(cc[:,1]))))+1
    cm = np.zeros((n_neurons, n_neurons))

    #
    for k in trange(cc.shape[0]):
        if cc[k,3]<1E-1:
            cm[int(cc[k,0]), int(cc[k,1])] = cc[k,2]

    cthresh = 0.3
    idx = np.where(cm>=cthresh)
    cm  =cm *0
    cm[idx] = 1

    # copy matrix
    cm = cm+cm.T
    
    return cm
    
#
def generate_graph(cm):
    adjacency_matrix = cm.copy()
    rows, cols = np.where(adjacency_matrix == 1)
    edges = zip(rows.tolist(), cols.tolist())
    G = nx.Graph()
    G.add_edges_from(edges)
    
    return G
    
    #nx.draw(gr, node_size=50, 
    #       # labels=mylabels, 
    #       # with_labels=True
    #       )
    #plt.show()
    
def get_degree_distribution(G):
    degrees = []
    for d in G.degree:
        degrees.append(d)

    # 
    degrees  = np.vstack(degrees)
    idx = np.argsort(degrees[:,0])
    degrees = degrees[idx]
    print (degrees)

    ds = degrees[:,1]
    y = np.histogram(ds, bins=np.arange(0,200,2))

    
    return y[1][:-1],y[0]


def get_animal_sessions(animal_id):
    df = pd.read_excel('/media/cat/4TB/donato/CA3 Wheel Animals Database.xlsx')

    #
    binarization_method='upphase'

    idx = np.where(df['Mouse_id']==animal_id)[0].squeeze()
    sessions = df.iloc[idx]['Session_ids'].split(',')
    print ("sessions: ", sessions)
    #
    cmap = plt.get_cmap("viridis", 10)
    ctr=0
    for k in range(len(sessions)):
        sessions[k] = sessions[k].replace(' ','')


    return sessions

####################
root_dir = '/media/cat/4TB/donato/'
animal_ids = [
    'DON-006084',
    'DON-006085',
    'DON-006087',
    'DON-003343',
    'DON-003165',
    'DON-002865'
]


cmap = plt.get_cmap("viridis", 10)
fig=plt.figure()

percentages = []
ave_degrees = []
mean_degree = []

for ctra, animal_id in enumerate(animal_ids):
    ax=plt.subplot(2,3,ctra+1)
    sessions = get_animal_sessions(animal_id)
    res = []
    mean_degree.append([])
    for ctr,session in enumerate(sessions):
        fname = os.path.join(root_dir,
                            animal_id, 
                            session,
                            'suite2p/plane0/cell_correlations.npy')
        #print ("fname", fname)
        cm = load_correlation_matrix(fname)
        G = generate_graph(cm)
        x, y = get_degree_distribution(G)
        plt.plot(x,y,
                color=cmap(ctr))
        res.append(y)
        
        #mean_degree[ctra].append(np.mean(y))
        mean_degree[ctra].append(np.median(y))
        
    y = np.median(np.vstack(res),axis=0)
    plt.plot(x,y,
                color='red',
            linewidth=3)
    ave_degrees.append(y)

   
    #
    plt.title(animal_id)
    if ctra%3==0:
        plt.ylabel("# of neurons")
    if ctr//3==1:
        plt.xlabel("degree")
    plt.xlim(1,200)
    plt.ylim(1,700)
    #
    plt.semilogx()
    plt.semilogy()
    
    ############################
    ax2 = ax.twinx()
    # 
    cumsum = np.cumsum(y)
    cumsum = cumsum/np.max(cumsum)
    percentages.append(cumsum)
    plt.plot(x,cumsum,
                color='black',
            linewidth=3)
    ax2.set_yticks(np.arange(0,1.1,.1))
    plt.ylim(0,1)
    ax2.set_ylabel("Percentage of neurons")
    #ax2.semilogy()
    
plt.show()
    

sessions:  ['20210519', ' 20210520', ' 20210521', ' 20210522', ' 20210523', ' 20210524', ' 20210525', ' 20210526', ' 20210527', ' 20210528']
(140715, 4)
[ 0.00000000e+00  1.00000000e+00 -4.53414669e-02  9.12829711e-27]


100%|███████████████████████████████████████████████████████████| 140715/140715 [00:00<00:00, 535537.08it/s]


[[  0 126]
 [  1  18]
 [  2   3]
 ...
 [528  23]
 [529  54]
 [530   7]]
(170236, 4)
[0.00000000e+000 1.00000000e+000 1.22255035e-001 1.49726929e-184]


100%|███████████████████████████████████████████████████████████| 170236/170236 [00:00<00:00, 474218.33it/s]


[[  0  76]
 [  1  24]
 [  2   3]
 ...
 [581 108]
 [582 100]
 [583 218]]
(110215, 4)
[ 0.00000000e+00  1.00000000e+00 -8.31161700e-02  5.06229971e-86]


100%|███████████████████████████████████████████████████████████| 110215/110215 [00:00<00:00, 464152.25it/s]


[[  0  51]
 [  1   4]
 [  2  12]
 [  3   9]
 [  4   7]
 [  5   9]
 [  6   5]
 [  7   9]
 [  8  13]
 [  9   8]
 [ 10  21]
 [ 11   3]
 [ 12  38]
 [ 13   1]
 [ 14   2]
 [ 15   9]
 [ 16  20]
 [ 17   2]
 [ 18   4]
 [ 19   6]
 [ 20   7]
 [ 21   9]
 [ 22   3]
 [ 23  19]
 [ 24  21]
 [ 25   5]
 [ 26   8]
 [ 27   9]
 [ 28  10]
 [ 29  33]
 [ 30   6]
 [ 31   2]
 [ 32  31]
 [ 33   7]
 [ 34  21]
 [ 35   1]
 [ 36   4]
 [ 37  16]
 [ 38   1]
 [ 39   9]
 [ 40   3]
 [ 41  27]
 [ 42  13]
 [ 44   2]
 [ 45   4]
 [ 46   3]
 [ 47  22]
 [ 48   5]
 [ 49   2]
 [ 50   4]
 [ 51   2]
 [ 52   2]
 [ 53   2]
 [ 54  28]
 [ 55  21]
 [ 56  33]
 [ 57   7]
 [ 58   3]
 [ 60   2]
 [ 61  18]
 [ 62  11]
 [ 63   1]
 [ 64   1]
 [ 65   6]
 [ 66   1]
 [ 67   8]
 [ 68   2]
 [ 69  15]
 [ 70  21]
 [ 71  49]
 [ 72  13]
 [ 73   5]
 [ 74   8]
 [ 75   5]
 [ 76  10]
 [ 77   8]
 [ 78   5]
 [ 79   2]
 [ 80   2]
 [ 81  15]
 [ 82   6]
 [ 83  26]
 [ 84  10]
 [ 85  11]
 [ 86  13]
 [ 87   4]
 [ 88   8]
 [ 89   4]
 [ 90   1]
 [ 91   6]
 [ 92   2]

100%|███████████████████████████████████████████████████████████| 126253/126253 [00:00<00:00, 439841.71it/s]


[[  0  80]
 [  1  81]
 [  2  81]
 [  3 137]
 [  4  69]
 [  5  42]
 [  6 114]
 [  7  91]
 [  8  99]
 [  9  46]
 [ 10   6]
 [ 11   4]
 [ 12   6]
 [ 13   1]
 [ 14  19]
 [ 15  31]
 [ 16   4]
 [ 17   9]
 [ 18  66]
 [ 19  43]
 [ 20  59]
 [ 21  80]
 [ 22 137]
 [ 23   5]
 [ 24   2]
 [ 25  18]
 [ 26  12]
 [ 27 118]
 [ 28 105]
 [ 29  33]
 [ 30 103]
 [ 31   2]
 [ 32 107]
 [ 33 122]
 [ 34  11]
 [ 35 103]
 [ 36  60]
 [ 37  74]
 [ 38  43]
 [ 39 138]
 [ 40  16]
 [ 41   9]
 [ 42 118]
 [ 43   2]
 [ 44   5]
 [ 45  27]
 [ 46  35]
 [ 47   1]
 [ 48  78]
 [ 49  83]
 [ 50 181]
 [ 51   6]
 [ 52  12]
 [ 53  37]
 [ 54   3]
 [ 55 114]
 [ 56 113]
 [ 57  48]
 [ 58  32]
 [ 59  61]
 [ 60  11]
 [ 61  41]
 [ 62 120]
 [ 63  70]
 [ 64 161]
 [ 65 136]
 [ 66  42]
 [ 67  46]
 [ 68  11]
 [ 69   2]
 [ 70 171]
 [ 71  50]
 [ 72  32]
 [ 73  18]
 [ 74  33]
 [ 75   5]
 [ 76  31]
 [ 77   1]
 [ 78 131]
 [ 79 156]
 [ 80 100]
 [ 81 163]
 [ 82   3]
 [ 83  95]
 [ 84  21]
 [ 85 128]
 [ 86  33]
 [ 87  10]
 [ 88   4]
 [ 89   3]
 [ 90 116]

100%|███████████████████████████████████████████████████████████| 148240/148240 [00:00<00:00, 476774.21it/s]


[[  0  74]
 [  1  82]
 [  2   4]
 ...
 [542  62]
 [543   5]
 [544   3]]
(42195, 4)
[0.         1.         0.01226872 0.00377224]


100%|█████████████████████████████████████████████████████████████| 42195/42195 [00:00<00:00, 390967.90it/s]


[[  0   5]
 [  1  41]
 [  2   5]
 [  3  10]
 [  4  11]
 [  5   3]
 [  6  10]
 [  7   2]
 [  8   2]
 [  9  26]
 [ 10  48]
 [ 11  31]
 [ 12  22]
 [ 13   2]
 [ 14  22]
 [ 15   2]
 [ 16  33]
 [ 17  33]
 [ 18   3]
 [ 19  22]
 [ 20   5]
 [ 21   5]
 [ 22  32]
 [ 23   2]
 [ 24   3]
 [ 25   7]
 [ 26  24]
 [ 27  45]
 [ 28   5]
 [ 29   9]
 [ 30   1]
 [ 31  10]
 [ 32  12]
 [ 33   6]
 [ 34  33]
 [ 35   6]
 [ 36  26]
 [ 37  10]
 [ 38   9]
 [ 39  13]
 [ 40   2]
 [ 41   1]
 [ 42  10]
 [ 43   3]
 [ 44  11]
 [ 45   3]
 [ 46  34]
 [ 47  30]
 [ 48   2]
 [ 49  37]
 [ 50  19]
 [ 51   6]
 [ 52  18]
 [ 53   6]
 [ 54   7]
 [ 55  20]
 [ 56   7]
 [ 57  48]
 [ 58  12]
 [ 59  29]
 [ 60   3]
 [ 61   1]
 [ 62  10]
 [ 63  38]
 [ 64   1]
 [ 65   9]
 [ 66   1]
 [ 67  33]
 [ 68   2]
 [ 69  49]
 [ 70   6]
 [ 71  81]
 [ 72   9]
 [ 73  43]
 [ 74  42]
 [ 75   1]
 [ 76  28]
 [ 77  59]
 [ 78   8]
 [ 79   2]
 [ 80  26]
 [ 81   1]
 [ 82  16]
 [ 83   3]
 [ 84   9]
 [ 85   4]
 [ 86   7]
 [ 87   9]
 [ 88   6]
 [ 89   1]
 [ 90  30]

100%|███████████████████████████████████████████████████████████| 106491/106491 [00:00<00:00, 409659.67it/s]


[[  0  95]
 [  1 105]
 [  2   1]
 [  3  19]
 [  4  83]
 [  5 100]
 [  6  83]
 [  7  34]
 [  8  88]
 [  9   6]
 [ 10   1]
 [ 11  98]
 [ 12  89]
 [ 13  91]
 [ 14  30]
 [ 15  13]
 [ 16  12]
 [ 17  98]
 [ 18   9]
 [ 19  56]
 [ 21   3]
 [ 22   8]
 [ 23   1]
 [ 24   4]
 [ 25  58]
 [ 26  16]
 [ 27  35]
 [ 28  94]
 [ 29  11]
 [ 30  73]
 [ 31 104]
 [ 32   1]
 [ 33  42]
 [ 34  30]
 [ 35  65]
 [ 36   1]
 [ 37   4]
 [ 39  26]
 [ 40  17]
 [ 41   5]
 [ 42  38]
 [ 43  55]
 [ 44  13]
 [ 45   1]
 [ 46   3]
 [ 47   3]
 [ 48  12]
 [ 49  11]
 [ 50  26]
 [ 51   3]
 [ 52  17]
 [ 53  32]
 [ 54  76]
 [ 55  13]
 [ 56   2]
 [ 57  26]
 [ 58   1]
 [ 59  42]
 [ 60   3]
 [ 61   6]
 [ 62  20]
 [ 63  15]
 [ 64  42]
 [ 65   9]
 [ 66   6]
 [ 67  14]
 [ 69  79]
 [ 70  57]
 [ 71  10]
 [ 72  17]
 [ 73   2]
 [ 74   5]
 [ 75   2]
 [ 76   3]
 [ 77   7]
 [ 78   5]
 [ 79  47]
 [ 80   4]
 [ 81   5]
 [ 83  81]
 [ 84   1]
 [ 85   5]
 [ 86  15]
 [ 87   3]
 [ 88  35]
 [ 89  28]
 [ 90   6]
 [ 91  78]
 [ 92   2]
 [ 93  81]
 [ 94  28]

100%|█████████████████████████████████████████████████████████████| 35778/35778 [00:00<00:00, 281139.98it/s]


[[  0  74]
 [  1  12]
 [  2   6]
 [  3  44]
 [  4  29]
 [  5  59]
 [  6  50]
 [  7  45]
 [  8  50]
 [  9  17]
 [ 10  23]
 [ 11  52]
 [ 12  63]
 [ 13  51]
 [ 14  48]
 [ 15  42]
 [ 16   3]
 [ 17   2]
 [ 18  12]
 [ 19  28]
 [ 20  60]
 [ 21   1]
 [ 22  60]
 [ 23  69]
 [ 24   4]
 [ 25   3]
 [ 26   5]
 [ 27  57]
 [ 28   2]
 [ 29   2]
 [ 30  38]
 [ 31  85]
 [ 32  47]
 [ 33  32]
 [ 34  14]
 [ 35  52]
 [ 36  21]
 [ 37  30]
 [ 38  26]
 [ 39  34]
 [ 40  15]
 [ 41  54]
 [ 42   7]
 [ 43  46]
 [ 44  75]
 [ 45  25]
 [ 46  35]
 [ 47  26]
 [ 48   7]
 [ 49  10]
 [ 50  11]
 [ 51  42]
 [ 52  80]
 [ 53  18]
 [ 54  28]
 [ 55   3]
 [ 56   7]
 [ 57  32]
 [ 58  69]
 [ 59  76]
 [ 60  38]
 [ 61  13]
 [ 62  50]
 [ 63  25]
 [ 64   8]
 [ 65  41]
 [ 66   1]
 [ 67   2]
 [ 68  52]
 [ 69  36]
 [ 70  28]
 [ 71  65]
 [ 72   9]
 [ 73  12]
 [ 74   1]
 [ 75  68]
 [ 76  45]
 [ 77  33]
 [ 78  53]
 [ 79   7]
 [ 80   6]
 [ 81  23]
 [ 82  32]
 [ 83   3]
 [ 84  15]
 [ 85  24]
 [ 86  21]
 [ 87  35]
 [ 88  77]
 [ 89  17]
 [ 90  19]

100%|███████████████████████████████████████████████████████████| 114960/114960 [00:00<00:00, 399636.97it/s]


[[  0  65]
 [  1  31]
 [  2  43]
 [  3  13]
 [  4  50]
 [  5   3]
 [  6   6]
 [  7  61]
 [  8  47]
 [  9  38]
 [ 10  11]
 [ 11  71]
 [ 12  12]
 [ 13  30]
 [ 14  13]
 [ 15  34]
 [ 16  17]
 [ 17  56]
 [ 18  37]
 [ 19  47]
 [ 20  19]
 [ 21  34]
 [ 22  22]
 [ 23  16]
 [ 24  34]
 [ 25  19]
 [ 26   9]
 [ 27   3]
 [ 28   4]
 [ 29  13]
 [ 30  23]
 [ 31   8]
 [ 32  23]
 [ 33  20]
 [ 34  17]
 [ 35  22]
 [ 36  75]
 [ 37   4]
 [ 38  13]
 [ 39  19]
 [ 40  35]
 [ 41   4]
 [ 42  16]
 [ 43  52]
 [ 44   8]
 [ 45  12]
 [ 46  13]
 [ 47  13]
 [ 48   6]
 [ 49  18]
 [ 50  31]
 [ 51  14]
 [ 52   6]
 [ 53  13]
 [ 54   6]
 [ 55  11]
 [ 56  17]
 [ 57   3]
 [ 58  34]
 [ 59  29]
 [ 60   8]
 [ 61   8]
 [ 62  18]
 [ 63   9]
 [ 64  16]
 [ 65  17]
 [ 66  13]
 [ 67  13]
 [ 68  41]
 [ 69  34]
 [ 70   4]
 [ 71   4]
 [ 72   1]
 [ 73  48]
 [ 74  48]
 [ 75  25]
 [ 76   5]
 [ 77  51]
 [ 78  19]
 [ 79   2]
 [ 80  10]
 [ 81  27]
 [ 82  28]
 [ 83  45]
 [ 84  27]
 [ 85   1]
 [ 86   3]
 [ 87  39]
 [ 88   2]
 [ 89   8]
 [ 90   1]

100%|█████████████████████████████████████████████████████████████| 77028/77028 [00:00<00:00, 364125.23it/s]


[[  0  72]
 [  1  78]
 [  2  65]
 [  3  60]
 [  4 117]
 [  5  41]
 [  6 105]
 [  7  56]
 [  8  28]
 [  9 123]
 [ 10  70]
 [ 11  94]
 [ 12  71]
 [ 13  90]
 [ 14  62]
 [ 15  47]
 [ 16  29]
 [ 17  49]
 [ 18  74]
 [ 19 122]
 [ 20  65]
 [ 21 109]
 [ 22  77]
 [ 23  89]
 [ 24  19]
 [ 25  53]
 [ 26 132]
 [ 27  82]
 [ 28 102]
 [ 29  25]
 [ 30 105]
 [ 31  60]
 [ 32  40]
 [ 33  92]
 [ 34  46]
 [ 35  58]
 [ 36 144]
 [ 37 140]
 [ 38  94]
 [ 39  26]
 [ 40   8]
 [ 41  40]
 [ 42  65]
 [ 43  95]
 [ 44   7]
 [ 45  29]
 [ 46  63]
 [ 47  91]
 [ 48  22]
 [ 49  19]
 [ 50  88]
 [ 51 145]
 [ 52  34]
 [ 53  64]
 [ 54  10]
 [ 55  36]
 [ 56  92]
 [ 57  72]
 [ 58  57]
 [ 59   5]
 [ 60  99]
 [ 61 115]
 [ 62  78]
 [ 63  72]
 [ 64   5]
 [ 65  67]
 [ 66  92]
 [ 67 100]
 [ 68  78]
 [ 69   7]
 [ 70  15]
 [ 71  17]
 [ 72  39]
 [ 73  13]
 [ 74   7]
 [ 75   5]
 [ 76 175]
 [ 77  33]
 [ 78  15]
 [ 79  43]
 [ 80  82]
 [ 81  61]
 [ 82  92]
 [ 83 120]
 [ 84  78]
 [ 85 113]
 [ 86  58]
 [ 87  22]
 [ 88  10]
 [ 89  76]
 [ 90  39]

100%|███████████████████████████████████████████████████████████| 758296/758296 [00:01<00:00, 566175.54it/s]


[[   0  123]
 [   1   20]
 [   2   87]
 ...
 [1229   22]
 [1230   15]
 [1231   95]]
(621055, 4)
[0.00000000e+00 1.00000000e+00 4.09278038e-02 4.17996421e-22]


100%|███████████████████████████████████████████████████████████| 621055/621055 [00:00<00:00, 645999.01it/s]


[[   0    6]
 [   1    8]
 [   2    5]
 ...
 [1111    1]
 [1113    1]
 [1114   39]]
(114003, 4)
[ 0.00000000e+00  1.00000000e+00 -8.31161700e-02  5.06229971e-86]


100%|███████████████████████████████████████████████████████████| 114003/114003 [00:00<00:00, 506147.10it/s]


[[  0  54]
 [  1   4]
 [  2  12]
 [  3   9]
 [  4   6]
 [  5   9]
 [  6   5]
 [  7   9]
 [  8  12]
 [  9   8]
 [ 10  23]
 [ 11   4]
 [ 12  37]
 [ 13   1]
 [ 14   2]
 [ 15   9]
 [ 16  23]
 [ 17   2]
 [ 18   4]
 [ 19   7]
 [ 20   7]
 [ 21   9]
 [ 22   3]
 [ 23  19]
 [ 24  22]
 [ 25   5]
 [ 26   8]
 [ 27   9]
 [ 28  10]
 [ 29  34]
 [ 30   6]
 [ 31   2]
 [ 32  30]
 [ 33   7]
 [ 34  21]
 [ 35   1]
 [ 36   4]
 [ 37  16]
 [ 38   1]
 [ 39  10]
 [ 40   3]
 [ 41  30]
 [ 42  14]
 [ 44   2]
 [ 45   4]
 [ 46   3]
 [ 47  21]
 [ 48   5]
 [ 49   2]
 [ 50   4]
 [ 51   2]
 [ 52   2]
 [ 53   2]
 [ 54  28]
 [ 55  21]
 [ 56  34]
 [ 57   7]
 [ 58   3]
 [ 60   1]
 [ 61  19]
 [ 62  11]
 [ 63   1]
 [ 64   1]
 [ 65   6]
 [ 66   1]
 [ 67  10]
 [ 68   2]
 [ 69  15]
 [ 70  21]
 [ 71  52]
 [ 72  13]
 [ 73   5]
 [ 74   7]
 [ 75   5]
 [ 76  10]
 [ 77   8]
 [ 78   4]
 [ 79   2]
 [ 80   2]
 [ 81  14]
 [ 82   6]
 [ 83  26]
 [ 84  10]
 [ 85  12]
 [ 86  13]
 [ 87   4]
 [ 88   8]
 [ 89   4]
 [ 90   1]
 [ 91   6]
 [ 92   2]

100%|█████████████████████████████████████████████████████████| 1353835/1353835 [00:01<00:00, 688239.65it/s]


[[   0    9]
 [   1   53]
 [   2    8]
 ...
 [1643  490]
 [1644    2]
 [1645  150]]
(697971, 4)
[0.00000000e+00 1.00000000e+00 2.93144318e-02 4.44461888e-12]


100%|███████████████████████████████████████████████████████████| 697971/697971 [00:01<00:00, 659336.14it/s]


[[   0    4]
 [   1   79]
 [   2    5]
 ...
 [1179  186]
 [1180    1]
 [1181  244]]
(696790, 4)
[0.         1.         0.67817283 0.        ]


100%|███████████████████████████████████████████████████████████| 696790/696790 [00:01<00:00, 647124.12it/s]


[[   0   79]
 [   1    7]
 [   2   25]
 ...
 [1178  349]
 [1179   29]
 [1180    1]]
(635628, 4)
[0.         1.         0.29502411 0.        ]


100%|███████████████████████████████████████████████████████████| 635628/635628 [00:01<00:00, 615485.87it/s]


[[   0   66]
 [   1  208]
 [   2  255]
 ...
 [1124   55]
 [1126  257]
 [1127    1]]
(542361, 4)
[0.00000000e+000 1.00000000e+000 1.03876936e-001 1.59099884e-133]


100%|███████████████████████████████████████████████████████████| 542361/542361 [00:00<00:00, 600205.35it/s]


[[   0   23]
 [   1  111]
 [   2   51]
 ...
 [1038   54]
 [1039   17]
 [1041  228]]
(527878, 4)
[0.         1.         0.83213748 0.        ]


100%|███████████████████████████████████████████████████████████| 527878/527878 [00:00<00:00, 624891.92it/s]


[[   0    7]
 [   1    4]
 [   2    6]
 ...
 [1025   60]
 [1026   39]
 [1027   63]]
(228150, 4)
[0.00000000e+00 1.00000000e+00 8.50932845e-02 4.36822962e-90]


100%|███████████████████████████████████████████████████████████| 228150/228150 [00:00<00:00, 535657.37it/s]


[[  0  20]
 [  1  26]
 [  2  23]
 ...
 [673  27]
 [674   4]
 [675  53]]
sessions:  ['20210524', ' 20210525', ' 20210526', ' 20210527', ' 20210528', ' 20210529', ' 20210530', ' 20210531', ' 20210601', ' 20210602']
(29890, 4)
[ 0.00000000e+00  1.00000000e+00 -8.05960618e-02  5.55715322e-81]


100%|█████████████████████████████████████████████████████████████| 29890/29890 [00:00<00:00, 406665.80it/s]


[[  0   1]
 [  1   8]
 [  2   1]
 [  3   6]
 [  4   2]
 [  5   5]
 [  6  25]
 [  7  11]
 [  8   2]
 [  9   6]
 [ 10   3]
 [ 11   1]
 [ 12   6]
 [ 13   8]
 [ 14   2]
 [ 15   1]
 [ 16   5]
 [ 17   5]
 [ 18   2]
 [ 19  36]
 [ 20   1]
 [ 21  24]
 [ 22   2]
 [ 23   2]
 [ 24   3]
 [ 26  16]
 [ 27   6]
 [ 29   3]
 [ 30  13]
 [ 31   6]
 [ 32   3]
 [ 34   9]
 [ 35   1]
 [ 36   3]
 [ 37   3]
 [ 38  18]
 [ 39  14]
 [ 40   4]
 [ 41   3]
 [ 42  10]
 [ 43  19]
 [ 45   1]
 [ 46  14]
 [ 47  22]
 [ 48  30]
 [ 49   9]
 [ 50   1]
 [ 51   4]
 [ 53   8]
 [ 54   1]
 [ 55  10]
 [ 56   5]
 [ 57   2]
 [ 58   1]
 [ 59   2]
 [ 60   7]
 [ 61   4]
 [ 62   1]
 [ 63   2]
 [ 64   5]
 [ 65   6]
 [ 66   2]
 [ 67   3]
 [ 68   3]
 [ 69  13]
 [ 70   3]
 [ 71   7]
 [ 72   2]
 [ 73   5]
 [ 74   5]
 [ 75   1]
 [ 76   1]
 [ 77   2]
 [ 78  16]
 [ 79   4]
 [ 80   8]
 [ 81   1]
 [ 82   3]
 [ 83   2]
 [ 84   1]
 [ 85   1]
 [ 86   4]
 [ 87   2]
 [ 89   9]
 [ 90   6]
 [ 91   7]
 [ 92   2]
 [ 93   3]
 [ 94   2]
 [ 95   2]
 [ 96   2]

100%|███████████████████████████████████████████████████████████| 101475/101475 [00:00<00:00, 484527.83it/s]


[[  0   5]
 [  1   4]
 [  2   6]
 [  3   5]
 [  4   3]
 [  5   2]
 [  6   2]
 [  7   5]
 [  8   3]
 [  9   4]
 [ 10   5]
 [ 11  10]
 [ 12  10]
 [ 13   1]
 [ 14   3]
 [ 15   2]
 [ 16   4]
 [ 17   3]
 [ 18   5]
 [ 19   2]
 [ 20   6]
 [ 21   4]
 [ 22   7]
 [ 23   2]
 [ 24   4]
 [ 25   5]
 [ 26   5]
 [ 27   2]
 [ 28   1]
 [ 29   1]
 [ 30   3]
 [ 31  11]
 [ 32   2]
 [ 33   4]
 [ 34   3]
 [ 35   3]
 [ 36   3]
 [ 37   9]
 [ 38   7]
 [ 39   1]
 [ 40   1]
 [ 41   4]
 [ 42   4]
 [ 43  10]
 [ 44   2]
 [ 45   1]
 [ 46   2]
 [ 47   2]
 [ 48   2]
 [ 49   1]
 [ 50   1]
 [ 51   6]
 [ 52   4]
 [ 53   2]
 [ 54   9]
 [ 55   3]
 [ 56   4]
 [ 57   1]
 [ 58   6]
 [ 59   6]
 [ 60  11]
 [ 61   2]
 [ 62   4]
 [ 63   1]
 [ 64   8]
 [ 65   4]
 [ 66   1]
 [ 67   3]
 [ 68   4]
 [ 69   3]
 [ 70  10]
 [ 71   2]
 [ 72   2]
 [ 73   3]
 [ 74   2]
 [ 75   2]
 [ 76   8]
 [ 77   2]
 [ 78  16]
 [ 79   3]
 [ 80   6]
 [ 81   1]
 [ 82   4]
 [ 83   1]
 [ 84   1]
 [ 85   5]
 [ 86   2]
 [ 87   2]
 [ 88   4]
 [ 89   5]
 [ 90   3]

100%|███████████████████████████████████████████████████████████| 210925/210925 [00:00<00:00, 507484.82it/s]


[[  0   6]
 [  1   4]
 [  2   7]
 ...
 [645   1]
 [647   4]
 [649   1]]
(170236, 4)
[ 0.00000000e+00  1.00000000e+00 -2.09696259e-02  7.37498777e-07]


100%|███████████████████████████████████████████████████████████| 170236/170236 [00:00<00:00, 544442.42it/s]


[[  0   8]
 [  1   2]
 [  2   4]
 ...
 [580   1]
 [581   1]
 [582   5]]
(306936, 4)
[0.         1.         0.00855526 0.04340093]


100%|███████████████████████████████████████████████████████████| 306936/306936 [00:00<00:00, 591905.62it/s]


[[  0  42]
 [  1   5]
 [  2  28]
 ...
 [781  18]
 [782   3]
 [783   7]]
(530965, 4)
[ 0.00000000e+00  1.00000000e+00 -6.02825506e-02  4.81986175e-46]


100%|███████████████████████████████████████████████████████████| 530965/530965 [00:00<00:00, 645890.53it/s]


[[   0    4]
 [   1    2]
 [   2    4]
 ...
 [1026    4]
 [1027    2]
 [1028    2]]
(1047628, 4)
[0.00000000e+00 1.00000000e+00 2.84835804e-02 1.74398435e-11]


100%|█████████████████████████████████████████████████████████| 1047628/1047628 [00:01<00:00, 682421.59it/s]


[[   0    4]
 [   1    5]
 [   2    2]
 ...
 [1445  412]
 [1446    1]
 [1447  140]]
(685035, 4)
[0.00000000e+00 1.00000000e+00 5.90052045e-02 3.49171015e-44]


100%|███████████████████████████████████████████████████████████| 685035/685035 [00:01<00:00, 676494.75it/s]


[[   0    2]
 [   1    2]
 [   2    1]
 ...
 [1167    1]
 [1168    1]
 [1169    2]]
(484620, 4)
[ 0.          1.         -0.00860084  0.04229634]


100%|███████████████████████████████████████████████████████████| 484620/484620 [00:00<00:00, 625382.04it/s]


[[  0   2]
 [  1   2]
 [  2   3]
 ...
 [980   5]
 [981   1]
 [982   1]]
(649230, 4)
[ 0.00000000e+00  1.00000000e+00 -7.17787126e-02  1.41737001e-64]


100%|███████████████████████████████████████████████████████████| 649230/649230 [00:00<00:00, 660495.40it/s]


[[   0    2]
 [   1    2]
 [   2    6]
 ...
 [1137    4]
 [1138    1]
 [1139    1]]
sessions:  ['DON-003343_20210213', ' DON-003343_20210214', ' DON-003343_20210215', ' DON-003343_20210216', ' DON-003343_20210217', ' DON-003343_20210218', ' DON-003343_20210219', ' DON-003343_20210220', ' DON-003343_20210221', ' DON-003343_20210222']
(352380, 4)
[ 0.          1.         -0.01357077  0.00135512]


100%|███████████████████████████████████████████████████████████| 352380/352380 [00:00<00:00, 556474.01it/s]


[[  0  10]
 [  1  57]
 [  2 108]
 ...
 [837  10]
 [838  11]
 [839   2]]
(354061, 4)
[0.00000000e+000 1.00000000e+000 1.09884687e-001 2.84527368e-149]


100%|███████████████████████████████████████████████████████████| 354061/354061 [00:00<00:00, 612617.55it/s]


[[  0   5]
 [  1   8]
 [  2   6]
 ...
 [839  59]
 [840 124]
 [841  10]]
(586986, 4)
[0.00000000e+00 1.00000000e+00 2.19724434e-02 2.12502482e-07]


100%|███████████████████████████████████████████████████████████| 586986/586986 [00:00<00:00, 636377.71it/s]


[[   0    5]
 [   1   18]
 [   2   13]
 ...
 [1081   58]
 [1082  350]
 [1083   90]]
(522753, 4)
[ 0.00000000e+00  1.00000000e+00 -6.34150993e-02  8.98048253e-51]


100%|███████████████████████████████████████████████████████████| 522753/522753 [00:00<00:00, 588751.72it/s]


[[   0    7]
 [   1    9]
 [   2   19]
 ...
 [1020   46]
 [1021   54]
 [1022   43]]
(302253, 4)
[0.         1.         0.22046737 0.        ]


100%|███████████████████████████████████████████████████████████| 302253/302253 [00:00<00:00, 587827.98it/s]


[[  0   6]
 [  1  10]
 [  2  12]
 ...
 [775  96]
 [776 120]
 [777  36]]
(146611, 4)
[ 0.00000000e+00  1.00000000e+00 -7.76771040e-02  2.44171142e-75]


100%|███████████████████████████████████████████████████████████| 146611/146611 [00:00<00:00, 526350.97it/s]


[[  0   7]
 [  1   8]
 [  2   1]
 ...
 [539  94]
 [540  95]
 [541  42]]
(352380, 4)
[ 0.00000000e+00  1.00000000e+00 -4.34204961e-04  9.18351443e-01]


100%|███████████████████████████████████████████████████████████| 352380/352380 [00:00<00:00, 612549.50it/s]


[[  0  15]
 [  1  11]
 [  2  18]
 ...
 [837  37]
 [838 281]
 [839  52]]
(388521, 4)
[ 0.00000000e+00  1.00000000e+00 -3.62398803e-02  1.14237793e-17]


100%|███████████████████████████████████████████████████████████| 388521/388521 [00:00<00:00, 579591.22it/s]


[[  0 139]
 [  1   6]
 [  2   8]
 ...
 [879 361]
 [880 353]
 [881  30]]
(182710, 4)
[0.00000000e+000 1.00000000e+000 1.17647314e-001 5.84001085e-171]


100%|███████████████████████████████████████████████████████████| 182710/182710 [00:00<00:00, 546671.27it/s]


[[  0   5]
 [  1  13]
 [  2   9]
 ...
 [602  37]
 [603  86]
 [604  20]]
(134421, 4)
[0.00000000e+000 1.00000000e+000 1.17647314e-001 5.84001085e-171]


100%|███████████████████████████████████████████████████████████| 134421/134421 [00:00<00:00, 522119.64it/s]


[[  0   4]
 [  1  16]
 [  2   5]
 ...
 [516   1]
 [517  21]
 [518  93]]
sessions:  ['DON-003165_20210211', ' DON-003165_20210213', ' DON-003165_20210215', ' DON-003165_20210216', ' DON-003165_20210217', ' DON-003165_20210218', ' DON-003165_20210219', ' DON-003165_20210220', ' DON-003165_20210222', ' DON-003165_20210223']
(215496, 4)
[0.00000000e+00 1.00000000e+00 9.75564604e-04 8.17843850e-01]


100%|███████████████████████████████████████████████████████████| 215496/215496 [00:00<00:00, 479904.12it/s]


[[  0  13]
 [  1  12]
 [  2  21]
 ...
 [654  32]
 [655  48]
 [656  67]]
(62481, 4)
[0.00000000e+000 1.00000000e+000 1.01771737e-001 3.20961451e-128]


100%|█████████████████████████████████████████████████████████████| 62481/62481 [00:00<00:00, 465630.52it/s]


[[  0  49]
 [  1  65]
 [  2  73]
 [  3 123]
 [  4 125]
 [  5  17]
 [  6  74]
 [  7  19]
 [  8  70]
 [  9  97]
 [ 10  66]
 [ 11 112]
 [ 12  31]
 [ 13  64]
 [ 14 106]
 [ 15 135]
 [ 16  64]
 [ 17  47]
 [ 18 122]
 [ 19 144]
 [ 20 148]
 [ 21 106]
 [ 22  40]
 [ 23 157]
 [ 24 129]
 [ 25 101]
 [ 26  68]
 [ 27 101]
 [ 28  91]
 [ 29 135]
 [ 30  14]
 [ 31  62]
 [ 32 143]
 [ 33  81]
 [ 34 137]
 [ 35  99]
 [ 36 115]
 [ 37 115]
 [ 38 104]
 [ 39   9]
 [ 40 115]
 [ 41 125]
 [ 42 155]
 [ 43  23]
 [ 44  41]
 [ 45  86]
 [ 46   8]
 [ 47   8]
 [ 48  99]
 [ 49 142]
 [ 50  29]
 [ 51  73]
 [ 52 101]
 [ 53 137]
 [ 54  36]
 [ 55  34]
 [ 56 139]
 [ 57 106]
 [ 58  12]
 [ 59  95]
 [ 60  62]
 [ 61 107]
 [ 62  35]
 [ 63 179]
 [ 64 110]
 [ 65  83]
 [ 66 102]
 [ 67 150]
 [ 68  51]
 [ 69 139]
 [ 70 173]
 [ 71 106]
 [ 72 144]
 [ 73  57]
 [ 74 159]
 [ 75 160]
 [ 76  73]
 [ 77  87]
 [ 78  27]
 [ 79 150]
 [ 80  83]
 [ 81 104]
 [ 82  20]
 [ 83 100]
 [ 84  99]
 [ 85  32]
 [ 86 175]
 [ 87 139]
 [ 88 132]
 [ 89 118]
 [ 90  91]

100%|█████████████████████████████████████████████████████████████| 56616/56616 [00:00<00:00, 446583.02it/s]


[[  0  10]
 [  1  10]
 [  2  13]
 [  3  85]
 [  4  52]
 [  5  78]
 [  6  63]
 [  7   8]
 [  8  75]
 [  9  22]
 [ 10   9]
 [ 11  82]
 [ 12  20]
 [ 13  58]
 [ 14  25]
 [ 15  34]
 [ 16   7]
 [ 17  77]
 [ 18  36]
 [ 19  37]
 [ 20  62]
 [ 21 101]
 [ 22  52]
 [ 23  13]
 [ 24  93]
 [ 25  36]
 [ 26  61]
 [ 27  66]
 [ 28  47]
 [ 29  21]
 [ 30  16]
 [ 31  65]
 [ 32  69]
 [ 33  11]
 [ 34  30]
 [ 35  76]
 [ 36  68]
 [ 37  23]
 [ 38  63]
 [ 39   5]
 [ 40  36]
 [ 41  21]
 [ 42  13]
 [ 43  43]
 [ 44  77]
 [ 45  74]
 [ 46  23]
 [ 47   1]
 [ 48  27]
 [ 49   6]
 [ 50   6]
 [ 51  89]
 [ 52  17]
 [ 53  20]
 [ 54  68]
 [ 55 104]
 [ 56  60]
 [ 57  99]
 [ 58  62]
 [ 59  43]
 [ 60  34]
 [ 61  59]
 [ 62   9]
 [ 63   4]
 [ 64  38]
 [ 65  17]
 [ 66 116]
 [ 67  84]
 [ 68  23]
 [ 69   8]
 [ 70  15]
 [ 71  23]
 [ 72  93]
 [ 73  15]
 [ 74  14]
 [ 75  36]
 [ 76   2]
 [ 77  94]
 [ 78  55]
 [ 79  19]
 [ 80  74]
 [ 81  49]
 [ 82  15]
 [ 83   6]
 [ 84  62]
 [ 85   2]
 [ 86  73]
 [ 87  87]
 [ 88 117]
 [ 89  75]
 [ 90  58]

100%|█████████████████████████████████████████████████████████████| 75466/75466 [00:00<00:00, 486024.50it/s]


[[  0  10]
 [  1  11]
 [  2  10]
 [  3  10]
 [  4  24]
 [  5  49]
 [  6  33]
 [  7   6]
 [  8   5]
 [  9  24]
 [ 10  64]
 [ 11   9]
 [ 12  48]
 [ 13  33]
 [ 14  25]
 [ 15  26]
 [ 16  42]
 [ 17  25]
 [ 18  18]
 [ 19   1]
 [ 20   9]
 [ 21   9]
 [ 22   3]
 [ 23  32]
 [ 24  21]
 [ 25  15]
 [ 26  16]
 [ 27  19]
 [ 28   7]
 [ 29  30]
 [ 30  16]
 [ 31  86]
 [ 32  63]
 [ 33  39]
 [ 34  54]
 [ 35  37]
 [ 36  13]
 [ 37  24]
 [ 38  49]
 [ 39  34]
 [ 40  27]
 [ 41   8]
 [ 42  30]
 [ 43   9]
 [ 44  67]
 [ 45 104]
 [ 46   5]
 [ 47  59]
 [ 48  10]
 [ 49  51]
 [ 50  25]
 [ 51  38]
 [ 52  21]
 [ 53   1]
 [ 54  42]
 [ 55  28]
 [ 56  15]
 [ 57   7]
 [ 58   7]
 [ 59   9]
 [ 60  14]
 [ 61  37]
 [ 62  52]
 [ 63  23]
 [ 64  32]
 [ 65  38]
 [ 66  21]
 [ 67  86]
 [ 68  34]
 [ 69  40]
 [ 70  36]
 [ 71  16]
 [ 72  10]
 [ 73  43]
 [ 74 104]
 [ 75   3]
 [ 76  26]
 [ 77  10]
 [ 78  32]
 [ 79  63]
 [ 80  29]
 [ 81   2]
 [ 82  41]
 [ 83  62]
 [ 84  25]
 [ 85  99]
 [ 86  32]
 [ 87  69]
 [ 88  87]
 [ 89  27]
 [ 90 116]

100%|█████████████████████████████████████████████████████████████| 79401/79401 [00:00<00:00, 495079.31it/s]


[[  0   2]
 [  1  57]
 [  2   3]
 [  3  54]
 [  4  21]
 [  5  18]
 [  6  10]
 [  7   9]
 [  8   4]
 [  9  10]
 [ 10  12]
 [ 11  25]
 [ 12  14]
 [ 13  43]
 [ 14  89]
 [ 15  14]
 [ 16  18]
 [ 17   6]
 [ 18   6]
 [ 19  34]
 [ 20  20]
 [ 21  25]
 [ 22  24]
 [ 23  21]
 [ 24  13]
 [ 25  13]
 [ 26   4]
 [ 27   5]
 [ 28   5]
 [ 29  15]
 [ 30   2]
 [ 31   5]
 [ 32   6]
 [ 33  15]
 [ 34  13]
 [ 35   8]
 [ 36  17]
 [ 37   6]
 [ 38  48]
 [ 39   8]
 [ 40   9]
 [ 41  39]
 [ 42   8]
 [ 43  36]
 [ 44  24]
 [ 45  30]
 [ 46  16]
 [ 47   6]
 [ 48  49]
 [ 49   4]
 [ 50  11]
 [ 51   2]
 [ 52  19]
 [ 53   8]
 [ 54   9]
 [ 55  19]
 [ 56  11]
 [ 57  13]
 [ 58  16]
 [ 59  12]
 [ 60   5]
 [ 61  19]
 [ 62  40]
 [ 63   8]
 [ 64 103]
 [ 65   9]
 [ 66  23]
 [ 67  31]
 [ 68  15]
 [ 69  58]
 [ 70   7]
 [ 71  17]
 [ 72  68]
 [ 73  66]
 [ 74  19]
 [ 75  11]
 [ 76  33]
 [ 77   5]
 [ 78  10]
 [ 79   2]
 [ 80  75]
 [ 81   8]
 [ 82  42]
 [ 83   5]
 [ 84   6]
 [ 85  56]
 [ 86  31]
 [ 87  13]
 [ 88  46]
 [ 89  20]
 [ 90   5]

100%|█████████████████████████████████████████████████████████████| 79401/79401 [00:00<00:00, 497479.13it/s]


[[  0  55]
 [  1  46]
 [  2  91]
 [  3  63]
 [  4  83]
 [  5  81]
 [  6  76]
 [  7  98]
 [  8  93]
 [  9 106]
 [ 10 127]
 [ 11 125]
 [ 12 106]
 [ 13 112]
 [ 14 128]
 [ 15  38]
 [ 16 108]
 [ 17  73]
 [ 18  82]
 [ 19 129]
 [ 20 145]
 [ 21  44]
 [ 22 100]
 [ 23  96]
 [ 24 118]
 [ 25  31]
 [ 26 119]
 [ 27  63]
 [ 28 129]
 [ 29  67]
 [ 30  52]
 [ 31  37]
 [ 32 111]
 [ 33  64]
 [ 34 116]
 [ 35 106]
 [ 36 120]
 [ 37 107]
 [ 38  88]
 [ 39 143]
 [ 40  29]
 [ 41 155]
 [ 42  81]
 [ 43 128]
 [ 44 113]
 [ 45 150]
 [ 46  42]
 [ 47  84]
 [ 48  88]
 [ 49 143]
 [ 50 112]
 [ 51  78]
 [ 52  79]
 [ 53 153]
 [ 54  95]
 [ 55  64]
 [ 56  52]
 [ 57 108]
 [ 58 168]
 [ 59  88]
 [ 60  31]
 [ 61 102]
 [ 62 118]
 [ 63 120]
 [ 64 148]
 [ 65 104]
 [ 66 148]
 [ 67  35]
 [ 68  55]
 [ 69  44]
 [ 70  75]
 [ 71 136]
 [ 72  91]
 [ 73 125]
 [ 74 120]
 [ 75 102]
 [ 76 193]
 [ 77  25]
 [ 78  52]
 [ 79  87]
 [ 80  59]
 [ 81 110]
 [ 82  81]
 [ 83 142]
 [ 84  49]
 [ 85  71]
 [ 86  58]
 [ 87  66]
 [ 88 120]
 [ 89  23]
 [ 90 172]

100%|█████████████████████████████████████████████████████████████| 46360/46360 [00:00<00:00, 421423.89it/s]


[[  0   9]
 [  1   8]
 [  2  12]
 [  3  11]
 [  4   6]
 [  5   2]
 [  6  14]
 [  7   2]
 [  8   5]
 [  9   7]
 [ 10  10]
 [ 11   2]
 [ 12   9]
 [ 13  10]
 [ 14  10]
 [ 15   4]
 [ 16   7]
 [ 17   4]
 [ 18   7]
 [ 19   4]
 [ 20  16]
 [ 21  12]
 [ 22  10]
 [ 23  29]
 [ 24  10]
 [ 25  11]
 [ 26   6]
 [ 27   3]
 [ 28  12]
 [ 30   6]
 [ 31  10]
 [ 32   4]
 [ 33  11]
 [ 34  11]
 [ 35  11]
 [ 36  23]
 [ 37  25]
 [ 38  19]
 [ 39  11]
 [ 40   9]
 [ 41   6]
 [ 42   4]
 [ 43  14]
 [ 44   7]
 [ 45   9]
 [ 46  22]
 [ 47   3]
 [ 48   2]
 [ 49  13]
 [ 50   9]
 [ 51  29]
 [ 52  22]
 [ 53   7]
 [ 54  24]
 [ 55  12]
 [ 56   8]
 [ 57   2]
 [ 58  10]
 [ 59  27]
 [ 60   1]
 [ 61   9]
 [ 62  11]
 [ 63   4]
 [ 64   6]
 [ 65  16]
 [ 66   9]
 [ 67   9]
 [ 68  22]
 [ 69   5]
 [ 70  24]
 [ 71  15]
 [ 72  18]
 [ 73  12]
 [ 74  11]
 [ 75  12]
 [ 76  43]
 [ 77  32]
 [ 78  30]
 [ 79   4]
 [ 80  16]
 [ 81   6]
 [ 82  24]
 [ 83  30]
 [ 84   4]
 [ 85  11]
 [ 86  28]
 [ 87  13]
 [ 88  13]
 [ 89  17]
 [ 90  16]
 [ 91  14]

100%|█████████████████████████████████████████████████████████████| 45150/45150 [00:00<00:00, 407235.00it/s]


[[  0 112]
 [  1 111]
 [  2 130]
 [  3 142]
 [  4 142]
 [  5 129]
 [  6 155]
 [  7 145]
 [  8 125]
 [  9 147]
 [ 10 144]
 [ 11 141]
 [ 12 163]
 [ 13  44]
 [ 14 175]
 [ 15   1]
 [ 16 139]
 [ 17 140]
 [ 18 151]
 [ 19 178]
 [ 20 140]
 [ 21 170]
 [ 22 201]
 [ 23  14]
 [ 24 121]
 [ 25 179]
 [ 26  63]
 [ 27 184]
 [ 28 192]
 [ 29 167]
 [ 30 106]
 [ 31 175]
 [ 32 167]
 [ 33 167]
 [ 34  65]
 [ 35 180]
 [ 36  43]
 [ 37  69]
 [ 38 180]
 [ 39 170]
 [ 40 193]
 [ 41  12]
 [ 42 190]
 [ 43   9]
 [ 44 175]
 [ 45 116]
 [ 46  12]
 [ 47   6]
 [ 48  11]
 [ 49 191]
 [ 50  24]
 [ 51 100]
 [ 52 129]
 [ 53 177]
 [ 54 156]
 [ 55 176]
 [ 56 181]
 [ 57 182]
 [ 58 177]
 [ 59 148]
 [ 60 146]
 [ 61 170]
 [ 62 176]
 [ 63   2]
 [ 64  20]
 [ 65 189]
 [ 66  49]
 [ 67 173]
 [ 68 168]
 [ 69 176]
 [ 71 160]
 [ 72 189]
 [ 73 183]
 [ 74 170]
 [ 75 124]
 [ 76 192]
 [ 77 189]
 [ 78 181]
 [ 79 197]
 [ 80 187]
 [ 81 187]
 [ 82 162]
 [ 83  10]
 [ 84 195]
 [ 85 168]
 [ 86 203]
 [ 87 190]
 [ 88 182]
 [ 89  95]
 [ 90 194]
 [ 91  13]

100%|█████████████████████████████████████████████████████████████| 51360/51360 [00:00<00:00, 453384.83it/s]


[[  0  21]
 [  1  10]
 [  2  20]
 [  3  10]
 [  4  35]
 [  5   3]
 [  6  23]
 [  7  27]
 [  8   5]
 [  9  17]
 [ 10  12]
 [ 11  10]
 [ 12   4]
 [ 13  23]
 [ 14  11]
 [ 15   6]
 [ 16  15]
 [ 17   5]
 [ 18   1]
 [ 19  14]
 [ 20  11]
 [ 21  11]
 [ 22   3]
 [ 23   9]
 [ 24  19]
 [ 25  53]
 [ 26  13]
 [ 27  63]
 [ 28  20]
 [ 29   4]
 [ 30  18]
 [ 31  14]
 [ 32  20]
 [ 33  19]
 [ 34   4]
 [ 35  13]
 [ 36  20]
 [ 37  16]
 [ 38  14]
 [ 39  23]
 [ 40  61]
 [ 41  61]
 [ 42   7]
 [ 43  18]
 [ 44  13]
 [ 45  36]
 [ 46   8]
 [ 47  35]
 [ 48   4]
 [ 49  24]
 [ 50  21]
 [ 51  23]
 [ 52  37]
 [ 53  19]
 [ 54   7]
 [ 55  32]
 [ 56   9]
 [ 57  10]
 [ 58  20]
 [ 59   8]
 [ 60  10]
 [ 61  26]
 [ 62  16]
 [ 63  53]
 [ 64  18]
 [ 65   5]
 [ 66  30]
 [ 67  10]
 [ 68   9]
 [ 69   8]
 [ 70  10]
 [ 71   5]
 [ 72   1]
 [ 73  14]
 [ 74   9]
 [ 75   9]
 [ 76  19]
 [ 77  31]
 [ 78  45]
 [ 79  14]
 [ 80  24]
 [ 81  14]
 [ 82  15]
 [ 83  40]
 [ 84  23]
 [ 85  13]
 [ 86  31]
 [ 87  85]
 [ 88   2]
 [ 89  11]
 [ 90  54]

100%|█████████████████████████████████████████████████████████████| 46360/46360 [00:00<00:00, 420194.47it/s]


[[  0   3]
 [  1   9]
 [  2  47]
 [  3  49]
 [  4  14]
 [  5  51]
 [  6   5]
 [  7   4]
 [  8  49]
 [  9   2]
 [ 10   8]
 [ 11   7]
 [ 12  51]
 [ 13   6]
 [ 14  11]
 [ 15  44]
 [ 16  46]
 [ 17   6]
 [ 18   4]
 [ 19  10]
 [ 20  11]
 [ 21  45]
 [ 22  40]
 [ 23   6]
 [ 24   4]
 [ 25  10]
 [ 26  44]
 [ 27  52]
 [ 28   4]
 [ 29  13]
 [ 30   7]
 [ 31  43]
 [ 32  42]
 [ 33  47]
 [ 34  25]
 [ 35  14]
 [ 36  35]
 [ 37   4]
 [ 38  12]
 [ 39   4]
 [ 40   6]
 [ 41  13]
 [ 42   8]
 [ 43  45]
 [ 44  11]
 [ 45   8]
 [ 46   2]
 [ 47   3]
 [ 48   2]
 [ 49   2]
 [ 50   7]
 [ 51  58]
 [ 52   8]
 [ 53   3]
 [ 54  58]
 [ 55   9]
 [ 56  46]
 [ 57   4]
 [ 58  44]
 [ 59  10]
 [ 60   3]
 [ 61  26]
 [ 62  58]
 [ 63   4]
 [ 64  46]
 [ 65  20]
 [ 66  36]
 [ 67  66]
 [ 68  26]
 [ 69   7]
 [ 70  33]
 [ 71  47]
 [ 72   8]
 [ 73   5]
 [ 74  27]
 [ 75  31]
 [ 76  10]
 [ 77  31]
 [ 78   7]
 [ 79   4]
 [ 80  13]
 [ 81   6]
 [ 82  23]
 [ 83   5]
 [ 84  48]
 [ 85  38]
 [ 86  18]
 [ 87  17]
 [ 88  17]
 [ 89  26]
 [ 90  20]

100%|███████████████████████████████████████████████████████████| 380628/380628 [00:00<00:00, 572456.91it/s]


[[  0  23]
 [  1  66]
 [  2  18]
 ...
 [870   3]
 [871  71]
 [872 227]]
(203841, 4)
[0.00000000e+00 1.00000000e+00 9.75564604e-04 8.17843850e-01]


100%|███████████████████████████████████████████████████████████| 203841/203841 [00:00<00:00, 491908.34it/s]


[[  0  12]
 [  1  12]
 [  2  20]
 ...
 [636  26]
 [637  47]
 [638  68]]
(257403, 4)
[ 0.00000000e+00  1.00000000e+00 -5.07927523e-02  3.58315326e-33]


100%|███████████████████████████████████████████████████████████| 257403/257403 [00:00<00:00, 581329.13it/s]


[[  0   3]
 [  1  19]
 [  2  47]
 ...
 [715  54]
 [716  59]
 [717  35]]
(261726, 4)
[ 0.00000000e+000  1.00000000e+000 -1.12257018e-001  9.70070507e-156]


100%|███████████████████████████████████████████████████████████| 261726/261726 [00:00<00:00, 587843.85it/s]


[[  0  14]
 [  1  10]
 [  2  42]
 ...
 [721  21]
 [722   4]
 [723  25]]
(571915, 4)
[0.         1.         0.67402045 0.        ]


100%|███████████████████████████████████████████████████████████| 571915/571915 [00:00<00:00, 640448.74it/s]


[[   0   47]
 [   1   67]
 [   2   31]
 ...
 [1067  305]
 [1068  260]
 [1069   10]]
(264628, 4)
[0.00000000e+00 1.00000000e+00 2.41949523e-02 1.11020017e-08]


100%|███████████████████████████████████████████████████████████| 264628/264628 [00:00<00:00, 549916.90it/s]


[[  0  48]
 [  1  25]
 [  2  14]
 ...
 [725  62]
 [726  40]
 [727  30]]
(223446, 4)
[0.00000000e+00 1.00000000e+00 5.85059827e-02 1.81628225e-43]


100%|███████████████████████████████████████████████████████████| 223446/223446 [00:00<00:00, 553457.43it/s]


[[  0  12]
 [  1   7]
 [  2  15]
 ...
 [666  25]
 [667  65]
 [668   3]]
(138075, 4)
[0.         1.         0.01377338 0.00114643]


100%|███████████████████████████████████████████████████████████| 138075/138075 [00:00<00:00, 432384.88it/s]


[[  0  39]
 [  1  21]
 [  2  22]
 ...
 [523  43]
 [524  21]
 [525  49]]
(299151, 4)
[ 0.0000000e+00  1.0000000e+00 -2.8946422e-02  8.1815121e-12]


100%|███████████████████████████████████████████████████████████| 299151/299151 [00:00<00:00, 531253.18it/s]


[[  0  20]
 [  1   8]
 [  2   4]
 ...
 [771  39]
 [772  14]
 [773  47]]
(406351, 4)
[0.         1.         0.39289939 0.        ]


100%|███████████████████████████████████████████████████████████| 406351/406351 [00:00<00:00, 608945.18it/s]


[[  0 130]
 [  1 192]
 [  2 127]
 ...
 [899 523]
 [900  35]
 [901  37]]


In [35]:
clrs = ['red','blue']
fig=plt.figure()
ax=plt.subplot(1,2,1)
for k in range(len(percentages)):
    plt.plot(percentages[k],
             color = clrs[k//3])
plt.ylabel("Cumulative % of cells")
plt.xlabel("Network degree")
#plt.semilogy()
#plt.semilogx()
#
ax=plt.subplot(1,2,2)
for k in range(len(percentages)):
    plt.plot(ave_degrees[k],
             color = clrs[k//3])
plt.ylabel("# of cells")
plt.xlabel("Network degree")

#plt.semilogy()
#plt.semilogx()

plt.show()



In [45]:

#
fig=plt.figure()
for k in range(len(mean_degree)):
    plt.plot(np.arange(10),mean_degree[k],
            color = clrs[k//3])
    
    
    
plt.show()


[[  0  76]
 [  1  24]
 [  2   3]
 ...
 [581 108]
 [582 100]
 [583 218]]
